export enum EnvConfiguration {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  CONNECTION_STRING = 'CONNECTION_STRING',
  JWT_LIFESPAN = 'JWT_LIFESPAN',
  TOKEN_SECRET = 'TOKEN_SECRET',
  SPOONACULAR_BASE_URL = 'SPOONACULAR_BASE_URL',
  SPOONACULAR_API_KEY = 'SPOONACULAR_API_KEY',
  SPOONACULAR_RATE_LIMIT = 'SPOONACULAR_RATE_LIMIT',
}
